name: Publicar en Discord (Servidores La Presa y Wiide)

on:
  schedule:
    - cron: '0 10 * * *' # Se ejecutará para ambos a las 10:00 UTC
  workflow_dispatch: 

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependencias
        run: pip install requests
        
      # Paso 1: Envío al Servidor La Presa
      - name: Publicar en Servidor La Presa
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_SERVIDOR_1 }}
        run: python discord/discord_bot.py

      # Paso 2: Envío al Servidor Wiide
      - name: Publicar en Servidor Wiide
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_SERVIDOR_2 }}
        run: python discord/discord_bot.py
